apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: public-api-vpa
  namespace: default
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: public-api
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        minAllowed:
          memory: 512Mi
          cpu: 500m
        maxAllowed:
          memory: 1Gi
          cpu: 1000m
        controlledResources: ["cpu", "memory"]
  updatePolicy:
    updateMode: "Off"