apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: smart-quiz-vpa
  namespace: default
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: smart-quiz
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        minAllowed:
          memory: 300Mi
          cpu: 500m
        maxAllowed:
          memory: 2Gi
          cpu: 900m
        controlledResources: ["cpu", "memory"]
  updatePolicy:
    updateMode: "Off"